name: cape-k-student-workshop-2025-dev
channels:
  - conda-forge
dependencies:
  - jupyter
  - mystmd
  - jupyterlab
  - xarray
  - matplotlib
  - dask
  - distributed
  - arm_pyart
  - act-atmos
  - metpy
  - siphon
  - cartopy
  - emc2
  - cmweather
  - myst-parser
  - pip
  - pip:
      - git+https://github.com/eagles-project/ESMAC_diags
